#CustomJoin V1.0
#This is my first plugin. Please be cool :P
#Author : Snorcky
#With help of http://bukkit.fr/ community

custom-message:
 join-msg: '&6%p&b est connecte'
 leave-msg: '&6%p&b quitte le serveur'
 welcome-msg '&e Bienvenue à &6%p&b sur notre serveur !' 
 
#"true" disable message when player join or leave the server.
 
disable:
 join: false
 leave: false
